
# Match Constants
EASY_MODE = 0
INTIMIDATE_MODE = 1
EXPERT_MODE = 2

MAX_WAITING_TIME = 10
MAX_RANK_DIFFERENCE = 2
MINIMUM_USERS_IN_WAITING_ROOM = 2
ADMIN = "yoni"
KEY = "yoni&itay"
ALGORITHM = "HS256"
TOKEN_TTL = 60
